[project]
name = "workflow"
version = "0.1.0"
description = "modul 2 DE zoomcamp"
requires-python = ">=3.12.12"
dependencies = [
    "pandas==2.3",
    "psycopg2-binary>=2.9.11",
    "pyarrow==16",
    "sqlalchemy>=2.0.46",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
